---
# tasks file for ubuntu24-sa-server-init
- name: Check OS version and family
  ansible.builtin.fail:
    msg: "This role can only be run against Ubuntu 24. {{ ansible_facts.distribution }} {{ ansible_facts.distribution_major_version }} is not supported."
  when:
    - ansible_facts.distribution == 'Ubuntu'
    - ansible_facts.distribution_major_version is version_compare('24', '!=')
  tags:
    - always

- name: Import cloud-init tasks
  ansible.builtin.import_tasks:
    file: 01_cloud_init/main.yml
  when: section_cloud_init
  tags:
    - always

- name: Import tasks for packages
  ansible.builtin.import_tasks:
    file: 02_packages/main.yml
  when: section_packages
  tags:
    - always

- name: Import tasks for cli
  ansible.builtin.import_tasks:
    file: 03_cli/main.yml
  when: section_cli
  tags:
    - always

- name: Import tasks for timezone and time synchronisation
  ansible.builtin.import_tasks:
    file: 04_time/main.yml
  when: section_time
  tags:
    - always

...
