---
- name: Only run update_cache if the last one is more than 3600 seconds ago
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: "{{ updates_cache_valid_time }}"
  tags:
    - always

- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest
    only_upgrade: true
  tags:
    - always

- name: Remove useless packages from the cache
  ansible.builtin.apt:
    autoclean: true
  tags:
    - always

- name: Remove dependencies that are no longer required and purge their configuration files
  ansible.builtin.apt:
    autoremove: true
    purge: "{{ updates_autoremove_purge }}"
  tags:
    - always

...
