---
- name: "02_packages | updates_tasks | Run update_cache if time > {{ updates_cache_valid_time }}"
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: "{{ updates_cache_valid_time }}"
  tags:
    - always

- name: "02_packages | updates_tasks | Update all packages to their latest version"
  ansible.builtin.apt:
    name: "*"
    state: latest
    only_upgrade: true
  tags:
    - always

- name: "02_packages | updates_tasks | Remove dependencies that are no longer required"
  ansible.builtin.apt:
    autoremove: true
    purge: "{{ updates_autoremove_purge }}"
  tags:
    - always

- name: "02_packages | updates_tasks | Remove useless packages from the cache"
  ansible.builtin.apt:
    autoclean: true
  tags:
    - always

...
