---
- name: "[APT:] Run update_cache (time > {{ updates_cache_valid_time }} seconds)"
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: "{{ updates_cache_valid_time }}"
  tags:
    - always

- name: "[APT:] Update all packages to their latest version"
  ansible.builtin.apt:
    name: "*"
    state: latest
    only_upgrade: true
  tags:
    - always

- name: "[APT:] Remove useless packages from the cache"
  ansible.builtin.apt:
    autoclean: true
  tags:
    - always

- name: "[APT:] Remove dependencies that are no longer required"
  ansible.builtin.apt:
    autoremove: true
    purge: "{{ updates_autoremove_purge }}"
  tags:
    - always

...
