---
# handlers file for ubuntu24-sa-server-init
- name: Restart crond service
  ansible.builtin.service:
    name: crond
    state: restarted

- name: Restart systemd-timesyncd service
  ansible.builtin.service:
    name: systemd-timesyncd
    state: restarted

- name: Restart systemd-journald service
  ansible.builtin.service:
    name: systemd-journald
    state: restarted

- name: Restart chronyd service
  ansible.builtin.service:
    name: chronyd
    state: restarted

...
