---
- name: Import tasks for MOTD
  ansible.builtin.import_tasks:
    file: motd_banners_tasks.yml
  tags:
    - always

- name: Import tasks for login banners
  ansible.builtin.import_tasks:
    file: login_banners_tasks.yml
  tags:
    - always

...
