---
- name: "01_cloud_init | cloud_init_tasks | Disable cloud-init ({{ cloud_init_disable_path }})"
  ansible.builtin.file:
    path: "{{ cloud_init_disable_path }}"
    state: touch
    mode: '0644'
    owner: root
    group: root
  when: cloud_init_disable
  tags:
    - always

...
