---
- name: "04_time | chrony_daemon_tasks | Stop systemd-timesync"
  ansible.builtin.service:
    name: systemd-timesyncd
    state: stopped
    enabled: false
  tags:
    - always

- name: "04_time | chrony_daemon_tasks | Install chrony package"
  ansible.builtin.apt:
    name: "chrony"
    state: present
  tags:
    - always

- name: "04_time | chrony_daemon_tasks | Create target folder ({{ time_chrony_path | dirname }})"
  ansible.builtin.file:
    path: "{{ time_chrony_path | dirname }}"
    state: directory
    mode: '0755'
  tags:
    - always

- name: "04_time | chrony_daemon_tasks | Apply NTP settings ({{ time_chrony_path }})"
  ansible.builtin.template:
    src: 04_time/chrony.conf.j2
    dest: "{{ time_chrony_path }}"
    mode: '0644'
    owner: root
    group: root
  notify:
    - Restart chronyd service
    - Restart cron service
    - Restart systemd-journald service
  tags:
    - always

...
