---
- name: "04_time | time_tasks | Install required package util-linux-extra"
  ansible.builtin.apt:
    name: "util-linux-extra"
    state: present
  tags:
    - always

- name: "04_time | time_tasks | Change time zone"
  community.general.timezone:
    name: "{{ time_timezone }}"
  notify:
    - Restart cron service
  tags:
    - always

...
