---
- name: Install required package util-linux-extra
  ansible.builtin.apt:
    name: "util-linux-extra"
    state: present
  tags:
    - always

- name: Change time zone
  community.general.timezone:
    name: "{{ time_timezone }}"
  notify:
    - Restart crond service
  tags:
    - always

...
