name: Ansible Lint

on:
  push:
    branches:
      - 'main'
      - 'development'
      - 'stable'
      - 'release/v*'
      - 'feature/*'
      - 'issue/*'
    paths-ignore:
      - '.github/workflows/*'
      - '**/*.md'
      - '**/*.txt'
  pull_request:
    branches:
      - 'main'
      - 'stable'
      - 'development'
      - 'release/v*'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Ansible Lint
    uses: dafneb/.github/.github/workflows/ansible-lint.yml@1b6bec269c61b9c3d09af73599b355011d3c2963
